[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"
solana_version = "3.0.10"

[features]
resolution = true
skip-lint = false

[programs.localnet]
sonar_clmm_dex = "FBDjF5uQ7Gyvz54757oLhirZJp34BhVGzzRyxvziSKru"

[programs.devnet]
sonar_clmm_dex = "FBDjF5uQ7Gyvz54757oLhirZJp34BhVGzzRyxvziSKru"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
